config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :boards, only: %i[index new create destroy show edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, length: { maximum: 255 }, presence: true
  validates :body, length: { maximum: 65_535 }, presence: true
  attr_accessor :eastern_mode # 仮想属性としてeastern_modeを追加
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def new
    @board = Board.new
  end
  
  def index
    # current_date = Date.today
    # formatted_date = current_date.strftime('%m月%d日')
    # begin
      # @chatgpt = ChatgptService.call("簡単に挨拶してください。その際、#{formatted_date}が誕生日の有名人を簡単に紹介してください。")
    # rescue Net::ReadTimeout
      # @chatgpt = "ようこそ！今日は#{formatted_date}です。"
    # end
    @boards = Board.all.order(created_at: :desc)
    @board = Board.new 
  end

  def show
    @board = Board.find(params[:id])
  end

  def create
    @board = Board.new(board_params)
    if params[:board][:western_mode] == '1'
      begin
        @board.body = ChatgptService.call("次の入力文を関西弁にしてください 入力文：#{@board.body}")
      rescue Net::ReadTimeout
      end
    end
    if @board.save
      redirect_to boards_path, success: I18n.t('defaults.message.created', item: Board.model_name.human)
    else
      flash.now['danger'] = I18n.t('defaults.message.not_created', item: Board.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

   def destroy
    @board = Board.find(params[:id])
    @board.destroy!
    redirect_to boards_path, status: :see_other, success: t('defaults.message.deleted', item: Board.model_name.human)
  end

  private

  def board_params
    params.require(:board).permit(:title, :body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.erb
<div class="card mt-3" style="width: 18rem;">
<div class="card-header">
    <%= board.title %>
  </div>
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted">
      
    </h6>
    <p class="card-text">
      <%= board.body %>
    </p>
  </div>
  <div class="text-end custom-footer mb-1">
    <small class="text-muted"><%= board.created_at.strftime("%Y-%m-%d %H:%M") %></small>
    <%= link_to 'Delete', board_path(board), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
      
    </div>
</div>

app/views/boards/index.html.erb
<div class="container-fluid mt-3">
<!--
<nav class="navbar navbar-light bg-light">
  <span class="navbar-text">
    <%= @chatgpt %>
  </span>
</nav>
-->
<div class="row mt-3">
  <div class="container-sm">
    <%= form_with model: @board, local: true do |form| %>
    <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control", id: "BoardTitle" %>
    </div>

    <div class="mb-3">
    <%= form.label :body, "Body", class: "form-label" %>
    <%= form.text_area :body, class: "form-control", id: "FormControlTextarea", rows: 3 %>
    </div>

    <div class="mb-3 form-check">
    <%= form.check_box :western_mode, class: "form-check-input", id: "Check" %>
    <%= form.label :western_mode, "Western Mode", class: "form-check-label" %>
    </div>

    <%= form.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  
  </div>
    <div class="container mt-5">
      <div class="row row-cols-2 mb-5">
        <!-- boardsが存在する場合 -->
        <% if @boards.present? %>
        <!-- パーシャルファイルで別途作成 -->
        <!-- @boards変数に含まれる各要素をパーシャルに渡す -->
        <%= render partial: "board", collection: @boards %>
        <% else %>
        <!-- 掲示板が存在しない場合にメッセージを表示する -->
        <% end %>
      </div>
    </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" class="footer-bottom bg-dark" data-bs-theme="dark">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-12">
        <div class="copyright">
          <p class="text-muted text-end">MaTTa@50B</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation bg-dark" data-bs-theme="dark">
    <%= link_to boards_path, class: 'navbar-brand'  do %>
    <%= image_tag 'logo.png', width:50 %>
    <%end %>
    <div class = "navbar-text">Sample App</div>
    <button
      class="navbar-toggler"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <li class="nav-item dropdown dropdown-slide">
          <%= link_to 'Board', boards_path, class: 'nav-link dropdown-toggle', data: {bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false'}, id: 'header-board-menu' %>
          <div class="dropdown-menu dropdown-menu-end">
            <%= link_to 'Boards index', boards_path, class: 'dropdown-item' %>
            <%= link_to 'Create Board', boards_path, class: 'dropdown-item' %>
          </div>
        </li>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/static_pages/top.html.erb
<div class="top-wrapper">
  <div class="top-inner-text">
    <%= link_to boards_path do %>
    <h1>Sample App</h1>
    <% end %>
  </div>
</div>